detect:
  log type: wel
  op: and
  rules:
  - case sensitive: false
    op: is
    path: Event/System/EventID
    value: '4697'
  - case sensitive: false
    op: contains
    path: Event/EventData/ServiceFileName
    value: '&&'
  - case sensitive: false
    op: contains
    path: Event/EventData/ServiceFileName
    value: rundll32
  - case sensitive: false
    op: contains
    path: Event/EventData/ServiceFileName
    value: shell32.dll
  - case sensitive: false
    op: contains
    path: Event/EventData/ServiceFileName
    value: shellexec_rundll
  - op: or
    rules:
    - case sensitive: false
      op: contains
      path: Event/EventData/ServiceFileName
      value: value
    - case sensitive: false
      op: contains
      path: Event/EventData/ServiceFileName
      value: invoke
    - case sensitive: false
      op: contains
      path: Event/EventData/ServiceFileName
      value: comspec
    - case sensitive: false
      op: contains
      path: Event/EventData/ServiceFileName
      value: iex
  target: log
respond:
- action: report
  metadata:
    author: Nikita Nazarov, oscd.community
    description: Detects Obfuscated Powershell via use Rundll32 in Scripts
    falsepositives:
    - Unknown
    level: high
    references:
    - https://github.com/Neo23x0/sigma/issues/1009
    tags:
    - attack.defense_evasion
    - attack.t1027
    - attack.execution
    - attack.t1059.001
  name: Invoke-Obfuscation Via Use Rundll32

