detect:
  events:
  - NEW_PROCESS
  - EXISTING_PROCESS
  op: and
  rules:
  - op: is windows
  - op: and
    rules:
    - op: or
      rules:
      - case sensitive: false
        op: ends with
        path: event/FILE_PATH
        value: \reg.exe
      - case sensitive: false
        op: is
        path: event/ORIGINAL_FILE_NAME
        value: reg.exe
    - case sensitive: false
      op: contains
      path: event/COMMAND_LINE
      value: \SOFTWARE\Policies\Microsoft\Windows\System
    - op: or
      rules:
      - case sensitive: false
        op: contains
        path: event/COMMAND_LINE
        value: GroupPolicyRefreshTimeDC
      - case sensitive: false
        op: contains
        path: event/COMMAND_LINE
        value: GroupPolicyRefreshTimeOffsetDC
      - case sensitive: false
        op: contains
        path: event/COMMAND_LINE
        value: GroupPolicyRefreshTime
      - case sensitive: false
        op: contains
        path: event/COMMAND_LINE
        value: GroupPolicyRefreshTimeOffset
      - case sensitive: false
        op: contains
        path: event/COMMAND_LINE
        value: EnableSmartScreen
      - case sensitive: false
        op: contains
        path: event/COMMAND_LINE
        value: ShellSmartScreenLevel
respond:
- action: report
  metadata:
    author: frack113
    description: Detect malicious GPO modifications can be used to implement many
      other malicious behaviors.
    falsepositives:
    - Legitimate use
    level: medium
    references:
    - https://github.com/redcanaryco/atomic-red-team/blob/40b77d63808dd4f4eafb83949805636735a1fd15/atomics/T1484.001/T1484.001.md
    tags:
    - attack.defense-evasion
    - attack.privilege-escalation
    - attack.t1484.001
  name: Modify Group Policy Settings

